### ISSUE TITLE
Installed but can't import lsmmdma

### ISSUE THREAD

**Issue by GangLiTarheel** [google-research/large_scale_mmdma#3]
[2022-12-02-lsmmdmaInstallation-forDebug.pdf](https://github.com/google-research/large_scale_mmdma/files/10143834/2022-12-02-lsmmdmaInstallation-forDebug.pdf)

Hi,

I tried to install and/or upgrade the recent version of lsmmdma and import it into Jupyter notebook. However, I failed to import even after several different approaches of installation (see the attached pdf). May I ask if you have any idea how to fix this?

Best,
Gang

**Comment by LaetitiaPapaxanthos** [comment]
Hi Gang,
Thank you for your message. I have just changed the requirements of the package so that it works with Colab and Jupyter notebooks. You can force to get the newest version of lsmmdma by doing `!pip install lsmmdma=0.1.11`. In case it still does not work, please let me know and I will reopen this issue.
